In [27]:
import numpy as np

In [28]:
# Defining the activation function 
# 
# Method Signature: 
#   - Definition: Takes the value and returns the sum upto one #   
#   - Parameters: Input Value(xin) 
#   - Return Value: Returns the value rounded upto 1

def sigmoid(X):
  return 1/(1 + np.exp(-X))

In [29]:
# The Neural Network Function
#
# Method Signature: 
#   - Definition: According to the number of epochs, this will train the neural
#                 network by feed-forward and backpropagation 
#   - Parameters: Input Matrice(X), Target Matrix(T), Weight Matrix(W1 & W2), learning_rate(learning_rate),
#                 number of iterations(num_epochs)
#   - Return Value: None 

def NN(X, T, W1, W2, learning_rate, num_epochs):
    for epoch in range(num_epochs):
        # Calculating output of the hidden layer
        l1_output = sigmoid(np.dot(X, W1))
        l2_output = sigmoid(np.dot(l1_output, W2))

        # Calculating error for the output layer
        l2_err = T - l2_output
        # Calculating the change in error for the ouput layer
        l2_delta = l2_err * l2_output * (1 - l2_output)
        
        # Calculating the error for the hidden layer
        l1_err = np.dot(l2_delta, W2.T)
        # Calculating the change in error for the hidden layer
        l1_delta = l1_err * l1_output * (1 - l1_output)

        # Backpropagating the error to find the change in weight
        W1 += learning_rate * np.dot(X.T, l1_delta)
        W2 += learning_rate * np.dot(l1_output.T, l2_delta)

In [30]:
# Defining the input and target matrix for the given neural network
X = np.array([[1, 1], [2, 2], [3, 3], [4, 2]])
T = np.array([[0, 1, 1, 0]]).T

In [31]:
# Defining input dimensions, dimensions of the hidden layer and that of the
# output layer
input_dim = 2
hidden_dim = 6
output_dim = 1

In [32]:
# Defining random matrices for the hidden layer and the output layer
W1 = np.random.random((input_dim, hidden_dim))
W2 = np.random.random((hidden_dim, output_dim))

In [33]:
# Running the neural network to get the weights after 2 iterations
NN(X, T, W1, W2, 0.2, 2)

In [34]:
# After running the Backpropagation Algorithm for 2 iterations we get the
# following value of W1 and W2
print(W1)
print(W2)

[[0.43297306 0.86909555 0.44489215 0.38216477 0.32430543 0.75499617]
 [0.47250039 0.09014887 0.21112341 0.0721057  0.16757344 0.37055557]]
[[0.69948344]
 [0.76297392]
 [0.97590915]
 [0.8485894 ]
 [0.01447041]
 [0.79289857]]


In [35]:
# Note; The following classifies the above datapoints, 
# and found the following weights after two iterations