In [20]:
import numpy as np

In [21]:
def activation(Y):
    return (Y >= 3).astype(int)

In [22]:
def NN(X, W, T, input_dim, output_dim):
    Y = activation(np.dot(X, W) + B)
    return W

In [23]:
input_dim = 2
output_dim = 1

In [24]:
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

In [25]:
T = np.array([[0, 0, 0, 1]]).T
T

array([[0],
       [0],
       [0],
       [1]])

In [26]:
W = np.array([[1.5, 1.5]]).T
B = 0
W

array([[1.5],
       [1.5]])

In [27]:
W = NN(X, W, T, input_dim, output_dim)

In [28]:
W

array([[1.5],
       [1.5]])

In [29]:
Y = activation(np.dot(X, W))
Y

array([[0],
       [0],
       [0],
       [1]])